default:
  development_stream2:
    DB_user: !expr Sys.getenv("DB_user")
    DB_password: !expr Sys.getenv("DB_password")
    DB_host: !expr Sys.getenv("DB_host")
    DB_port: !expr Sys.getenv("DB_port")
    DB_name: !expr Sys.getenv("DB_name")
    Dhis2_username: !expr Sys.getenv("Dhis2_username")
    Dhis2_password: !expr Sys.getenv("Dhis2_password")
    Dhis2_base_url: !expr Sys.getenv("Dhis2_base_url")

