---
title: "appending_remote_database_meningitis"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{appending_remote_database_meningitis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(Dhis2WithSormas)
library(readr)
```

```{r}

input <- list(year = "2024", month = "05")

dw <- config::get("development_stream2")

connection <- DBI::dbConnect(RMariaDB::MariaDB(),
               username = dw$DB_user,
               password = dw$DB_password,
               host     = dw$DB_host,
               port     = dw$DB_port,
               dbname   = dw$DB_name)

```

## Confirmed Meningitis cases, Meningitis coverage, Alt D

```{r}
sormas_meningitis_cleaned <- sormas_cleaner("/Volumes/Robinson/Afenet-projects/afenet-nigeria/Dhis2WithSormas/data-raw/sormas_meningitis_cases_Apr_2024.csv", disease = "meningitis (csm)")
```

```{r}
#men_A_coverage_monthly <- read_csv("/Volumes/Robinson/Afenet-projects/afenet-nigeria/Dhis2WithSormas/data-raw/meningitis_coverage_monthly.csv")


men_A_coverage_monthly <-getAnalytics_cleaned(indicator_id = "SruoPzzt3ES",
                       months = input$month,
                       year = input$year,
                       organisation_uint = c("LEVEL-1", "LEVEL-2","LEVEL-3"))
```

```{r}
#men_A_given <- read_csv("/Volumes/Robinson/Afenet-projects/afenet-nigeria/Dhis2WithSormas/data-raw/men_A_given.csv")

men_A_given <-  getAnalytics_cleaned(indicator_id = "iOUKrRANJwi",
                       months = input$month,
                       year = input$year,
                       organisation_uint = c("LEVEL-1", "LEVEL-2","LEVEL-3"))

```

```{r}

men_A_alt_denominator <- get_alt_denominator(coverage = men_A_coverage_monthly,
                    sormas_cleaned = sormas_meningitis_cleaned ,
                    doses_given = men_A_given, 
                    denominator_data = denominator_data)

dbAppendTable(connection , name = "men_A_alt_denominator2", value = men_A_alt_denominator )

```

## Age Group of Confirmed Meningitis Cases by Vaccination Status

```{r}

meningitis_age_group <- get_age_group(sormas_cleaned = sormas_meningitis_cleaned)

dbAppendTable(connection, name = "meningitis_age_group", value = meningitis_age_group )


```

## Men A Stock Analysis & Men A given

```{r}
#men_A_received <- read_csv("/Volumes/Robinson/Afenet-projects/afenet-nigeria/Dhis2WithSormas/data-raw/men_A_Received.csv")


men_A_received  <- getAnalytics_cleaned(indicator_id = "yH7RI3urgYi",
                       months = input$month,
                       year = input$year,
                       organisation_uint = c("LEVEL-1", "LEVEL-2","LEVEL-3")
                       )


```

```{r}
#men_A_opening_balance <- read_csv("/Volumes/Robinson/Afenet-projects/afenet-nigeria/Dhis2WithSormas/data-raw/men_A_OB.csv")


men_A_opening_balance  <-  getAnalytics_cleaned(indicator_id = "BWBsbKHaCrz",
                       months = input$month,
                       year = input$year,
                       organisation_uint = c("LEVEL-1", "LEVEL-2","LEVEL-3")
                       )




```

```{r}
#men_A_opened_used <- read_csv("/Volumes/Robinson/Afenet-projects/afenet-nigeria/Dhis2WithSormas/data-raw/men_A_Doses_Opened.csv")

men_A_opened_used  <- getAnalytics_cleaned(indicator_id = "snrl5tiWGLE",
                       months = input$month,
                       year = input$year,
                       organisation_uint = c("LEVEL-1", "LEVEL-2","LEVEL-3")
                       )

```

```{r}
men_A_stock_analysis <- get_stock_analysis(doses_given = men_A_given,
                                        received = men_A_received,
                                        opening_balance = men_A_opening_balance,
                                        opened_used = men_A_opened_used)

dbAppendTable(connection, name = "men_A_stock_analysis", value = men_A_stock_analysis )

```

## Co-administered Antigen Discrepancy: MCV 1 & Men A given by State

```{r}

#measles1_given <- read_csv("/Volumes/Robinson/Afenet-projects/afenet-nigeria/Dhis2WithSormas/data-raw/measles1_given.csv")

measles1_given <- getAnalytics_cleaned(indicator_id = "j6mCLL1X4yG",
                        months = input$month,
                       year = input$year,
                       organisation_uint = c("LEVEL-1", "LEVEL-2","LEVEL-3"))

```

```{r}
measles_men_A_discrepancy <- get_discrepancy(main_vaccine_given = measles1_given, 
                                                        other_vaccine_given = men_A_given)


dbAppendTable(connection, name = "measles_men_A_discrepancy", value = measles_men_A_discrepancy )

```

## Map Confirmed Meningitis cases, Meningitis coverage

## Map Confirmed men_A cases, MCV 1 coverage

```{r}
#men_A_coverage_annually <- read_csv("/Volumes/Robinson/Afenet-projects/afenet-nigeria/Dhis2WithSormas/data-raw/meningitis_coverage_annualized.csv")

men_A_coverage_annually <- getAnalytics_cleaned(indicator_id = "SruoPzzt3ES",
                       months = c(),
                      year = input$year,
                       organisation_uint = c("LEVEL-1", "LEVEL-2","LEVEL-3")
                       )

```

```{r}
men_A_coverage_map <- get_coverage_map(annual_data = men_A_coverage_annually,
                 monthly_data = men_A_coverage_monthly)

dbAppendTable(connection, name = "men_A_coverage_map", value = men_A_coverage_map )

```

```{r}
meningitis_cases_map <- sormas_meningitis_cleaned%>%
  select("##Case ID","Disease", "Long", "Lat", "Months", "Year", "State", "LGA")


dbAppendTable(connection, name = "meningitis_cases_map",value = meningitis_cases_map )


```
