---
title: "appending_remote_database_diphtheria"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{appending_remote_database_diphtheria}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(Dhis2WithSormas)
library(readr)
```

```{r}

input <- list(year = "2024", month = "05")

dw <- config::get("development_stream2")

connection <- DBI::dbConnect(RMariaDB::MariaDB(),
               username = dw$DB_user,
               password = dw$DB_password,
               host     = dw$DB_host,
               port     = dw$DB_port,
               dbname   = dw$DB_name
            )

```



## Confirmed diphtheria cases, Penta 1, Penta 3

```{r}
diphtheria_sormas_cleaned <- sormas_cleaner("/Volumes/Robinson/Afenet-projects/afenet-nigeria/Dhis2WithSormas/data-raw/sormas_diphtheria_cases_May_2024.csv", disease = "diphtheria")

```


```{r}

penta1_coverage_monthly <- getAnalytics_cleaned(indicator_id = "yHw3A23QqP8",
                       months = input$month,
                       year = input$year,
                       organisation_uint = c("LEVEL-1","LEVEL-2","LEVEL-3")
                       )

```


```{r}

penta3_coverage_monthly <- getAnalytics_cleaned(indicator_id = "VRycpXG44y1",
                      months = input$month,
                       year = input$year,
                       organisation_uint = c("LEVEL-1", "LEVEL-2","LEVEL-3"))
```


```{r}
penta1_given <- getAnalytics_cleaned(indicator_id = "b6X0aWFCb2E",
                        months = input$month,
                       year = input$year,
                       organisation_uint = c("LEVEL-1", "LEVEL-2","LEVEL-3"))


```

```{r}


penta2_given <- getAnalytics_cleaned(indicator_id = "x4HgjBU1kCq",
                        months = input$month,
                       year = input$year,
                       organisation_uint = c("LEVEL-1", "LEVEL-2","LEVEL-3"))
```


```{r}

penta3_given <- getAnalytics_cleaned(indicator_id = "BFeSKtHhPKi",
                      months = input$month,
                       year = input$year,
                       organisation_uint = c("LEVEL-1", "LEVEL-2","LEVEL-3"))
```


```{r}
diphtheria_alt_denominator <- get_2_dose_alt_denominator(sormas_cleaned = diphtheria_sormas_cleaned,
                            first_dose = penta1_coverage_monthly,
                            later_dose = penta3_coverage_monthly,
                            first_dose_given = penta1_given,
                            later_dose_given = penta3_given,
                            denominator_data = denominator_data)

dbAppendTable(connection , name = "diphtheria_alt_denominator", value = diphtheria_alt_denominator )

```




# Age group 

```{r}

diphtheria_age_group <- get_age_group(sormas_cleaned = diphtheria_sormas_cleaned)

dbAppendTable(connection, name = "diphtheria_age_group", value = diphtheria_age_group )

```

# Chart 3: Penta Stock Analysis & Penta (1 & 3) given


```{r}
penta_1_3_given <- add_three_dose_antigen_given(first_dose_given = penta1_given,
                                                second_dose_given = penta2_given,
                                                third_dose_given = penta3_given,
                                                      antigen = "Penta")
```

```{r}
penta_received <-  getAnalytics_cleaned(indicator_id = "KrI2GAlgMsI",
                       months = input$month,
                       year = input$year,
                       organisation_uint = c("LEVEL-1", "LEVEL-2","LEVEL-3"))


penta_opening_balance <- getAnalytics_cleaned(indicator_id = "XeEhY1acJ7p",
                       months = input$month,
                       year = input$year,
                       organisation_uint = c("LEVEL-1", "LEVEL-2","LEVEL-3"))


penta_opened_used <- getAnalytics_cleaned(indicator_id = "P6zdm7C653N",
                       months = input$month,
                       year = input$year,
                       organisation_uint = c("LEVEL-1", "LEVEL-2","LEVEL-3"))


```

```{r}
penta_stock_analysis <- get_stock_analysis(doses_given = penta_1_3_given,
                                        received = penta_received,
                                        opening_balance = penta_opening_balance,
                                        opened_used = penta_opened_used)

dbAppendTable(connection, name = "penta_stock_analysis", value = penta_stock_analysis)
```

## Chart 5 : Penta 1, Penta 3 Coverage & Drop Out Rate
```{r}
penta1_penta3_dropout_rate <- get_drop_out_rate(first_dose  = penta1_coverage_monthly,
                                              later_dose =  penta3_coverage_monthly)

dbAppendTable(connection, name = "penta1_penta3_dropout_rate", value = penta1_penta3_dropout_rate )
```


## Co-administered Antigen Discrepancy: Penta 1 & OPV1 given by State

```{r}
opv1_given <- getAnalytics_cleaned(indicator_id = "HhWjY78dECn",
                        months = input$month,
                       year = input$year,
                       organisation_uint = c("LEVEL-1", "LEVEL-2","LEVEL-3"))
```


```{r}

penta1_opv1_discrepancy <- get_discrepancy(main_vaccine_given = penta1_given, 
                                                        other_vaccine_given = opv1_given)


dbAppendTable(connection, name = "penta1_opv1_discrepancy", value = penta1_opv1_discrepancy )
```

## Map Confirmed Diphtheria cases, Penta 1 coverage


```{r}
penta1_coverage_annually <- getAnalytics_cleaned(indicator_id =  "yHw3A23QqP8",
                      months = c(),
                       year = input$year,
                      organisation_uint = c("LEVEL-1", "LEVEL-2","LEVEL-3")
                       )

```


```{r}
penta_coverage_map <- get_coverage_map(annual_data = penta1_coverage_annually,
                 monthly_data = penta1_coverage_monthly)

dbAppendTable(connection, name = "penta_coverage_map",value = penta_coverage_map)
```


```{r}
diphtheria_cases_map <- diphtheria_sormas_cleaned  %>%
  select("##Case ID","Disease", "Long", "Lat", "Months", "Year", "State", "LGA")


dbAppendTable(connection, name = "diphtheria_cases_map", value = diphtheria_cases_map)

```


