---
title: "appending_remote_database_measles"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{appending_remote_database_measles}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(Dhis2WithSormas)
library(readr)
```

```{r}

input <- list(year = "2023", month = "08")

dw <- config::get("development_stream2")

connection <- DBI::dbConnect(RMariaDB::MariaDB(),
               username = dw$DB_user,
               password = dw$DB_password,
               host     = dw$DB_host,
               port     = dw$DB_port,
               dbname   = dw$DB_name
            )

```



## Confirmed Measles cases, MCV1, MCV2 and cases

```{r}
#measles_sormas_cleaned <- sormas_cleaner("/Volumes/Robinson/Afenet-projects/afenet-nigeria/Dhis2WithSormas/data-raw/sormas_measles.csv")

measles_sormas_cleaned <- sormas_cleaner("/Volumes/Robinson/Afenet-projects/afenet-nigeria/Dhis2WithSormas/data-raw/sormas_measles_cases_2017_August_2023.csv", disease = "measles")

```


```{r}

measles1_coverage_monthly <- getAnalytics_cleaned(indicator_id = "tb5NGUMB9dQ",
                       months = input$month,
                       year = input$year,
                       organisation_uint = c("LEVEL-1","LEVEL-2","LEVEL-3")
                       )

```


```{r}


measles2_coverage_monthly <- getAnalytics_cleaned(indicator_id = "qagHWllYle8",
                      months = input$month,
                       year = input$year,
                       organisation_uint = c("LEVEL-1", "LEVEL-2","LEVEL-3"))
```


```{r}

measles1_given <- getAnalytics_cleaned(indicator_id = "j6mCLL1X4yG",
                        months = input$month,
                       year = input$year,
                       organisation_uint = c("LEVEL-1", "LEVEL-2","LEVEL-3"))


```


```{r}
#measles2_given <-read_csv("/Volumes/Robinson/Afenet-projects/afenet-nigeria/Dhis2WithSormas/data-raw/measles2_given.csv")

measles2_given <- getAnalytics_cleaned(indicator_id = "oB7SLTRHciH",
                      months = input$month,
                       year = input$year,
                       organisation_uint = c("LEVEL-1", "LEVEL-2","LEVEL-3"))
```


```{r}
measles_alt_denominator <- get_2_dose_alt_denominator(sormas_cleaned = measles_sormas_cleaned,
                                                       first_dose = measles1_coverage_monthly,
                                                       later_dose = measles2_coverage_monthly,
                                                       first_dose_given = measles1_given,
                                                       later_dose_given = measles2_given,
                                                       denominator_data = denominator_data)

# [1] "Measles 1 given"           "State"                     "LGA"                       "Months"                   
#  [5] "Year"                      "Measles 2 given"           "MCV 1 Alt Denominator"     "MCV 2 Alt Denominator"    
#  [9] "MCV 1"                     "MCV 2"                     "Measles Cases (CaseBased)"



dbAppendTable(connection , name = "measles_alt_denominator", value = measles_alt_denominator )

```

# Age group 

```{r}

measles_age_group <- get_age_group(sormas_cleaned = measles_sormas_cleaned)

dbAppendTable(connection, name = "measles_age_group", value = measles_age_group )


```

# Chart 3: MCV Stock Analysis & MCV (1 & 2) given


```{r}
measles_1_2_given <- add_measles_1_2_given(measles1_given = measles1_given,measles2_given = measles2_given)

#measles_received <- read_csv("/Volumes/Robinson/Afenet-projects/afenet-nigeria/Dhis2WithSormas/data-raw/measles_Received.csv")
measles_received <-  getAnalytics_cleaned(indicator_id = "XklyJxzoyxR",
                        months = input$month,
                       year = input$year,
                       organisation_uint = c("LEVEL-1", "LEVEL-2","LEVEL-3"))
```


```{r}
#measles_opening_balance <- read_csv("/Volumes/Robinson/Afenet-projects/afenet-nigeria/Dhis2WithSormas/data-raw/measles_OB.csv")

measles_opening_balance <- getAnalytics_cleaned(indicator_id = "vtHJVTAguch",
                          months = input$month,
                       year = input$year,
                       organisation_uint = c("LEVEL-1", "LEVEL-2","LEVEL-3"))
```


```{r}
#measles_opened_used <- read_csv("/Volumes/Robinson/Afenet-projects/afenet-nigeria/Dhis2WithSormas/data-raw/measles_opened_used.csv")


measles_opened_used<- getAnalytics_cleaned(indicator_id = "hg1D2tXg3aB",
                       months = input$month,
                       year = input$year,
                       organisation_uint = c("LEVEL-1", "LEVEL-2","LEVEL-3"))

```


```{r}

measles_stock_analysis <- get_stock_analysis(doses_given = measles_1_2_given,
                                        received = measles_received,
                                        opening_balance = measles_opening_balance,
                                        opened_used = measles_opened_used)

dbAppendTable(connection, name = "measles_stock_analysis", 
              value = measles_stock_analysis )


```

## MCV 1, MCV 2 Coverage & Drop Out Rate


```{r}
mcv1_mcv2_dropout_rate <- get_drop_out_rate(first_dose  = measles1_coverage_monthly,
                                            second_dose =  measles2_coverage_monthly)

dbAppendTable(connection, name = "mcv1_mcv2_dropout_rate", value = mcv1_mcv2_dropout_rate )



```

## Co-administered Antigen Discrepancy: MCV 1 & Yellow Fever given by State

```{r}
#yf_vaccine_given <- read_csv("/Volumes/Robinson/Afenet-projects/afenet-nigeria/Dhis2WithSormas/data-raw/yf_Vaccine_Given.csv")

yf_vaccine_given <- getAnalytics_cleaned(indicator_id = "KpKx2MosfIV",
                      months = input$month,
                       year = input$year,
                       organisation_uint = c("LEVEL-1", "LEVEL-2","LEVEL-3")
                       )
```


```{r}

measles_yf_discrepancy <- get_discrepancy(main_vaccine_given = measles1_given, 
                                                        other_vaccine_given = yf_vaccine_given)


dbAppendTable(connection, name = "measles_yf_discrepancy", value = measles_yf_discrepancy )

```

## National MCV Coverage (%) by different sources, Nigeria (National)

```{r}
#measles1_coverage_annualized_all_time <- read_csv("/Volumes/Robinson/Afenet-projects/afenet-nigeria/Dhis2WithSormas/data-raw/measles1_coverage_annualized_all_time.csv")

measles1_coverage_annualized_all_time <- getAnalytics_cleaned(indicator_id = "hvYqrmR6MPq",
                       months = c(),
                       year = input$year,
                       organisation_uint = "LEVEL-1")
  
```


```{r}
#measles2_coverage_annualized_all_time <- read_csv("/Volumes/Robinson/Afenet-projects/afenet-nigeria/Dhis2WithSormas/data-raw/measles2_coverage_annualized_all_time.csv")

measles2_coverage_annualized_all_time <- getAnalytics_cleaned(indicator_id = "Fbj3AkYjCie",
                                                              months = c(),
                                                              year = input$year,
                                                              organisation_uint = "LEVEL-1")
 
```


```{r}
# Data aggregated by Year, State

mcv_different_sources <- get_mcv_different_sources(mcv1_annualized_all_time = measles1_coverage_annualized_all_time,
                                                   mcv2_annualized_all_time = measles2_coverage_annualized_all_time)

dbWriteTable(connection, name = "mcv_different_sources", value = mcv_different_sources, overwrite = T)

```

## Map Confirmed Measles cases, MCV 1 coverage


```{r}
#measles1_coverage_annually <- read_csv("/Volumes/Robinson/Afenet-projects/afenet-nigeria/Dhis2WithSormas/data-raw/measles1_coverage_annualized.csv")

measles1_coverage_annually <- getAnalytics_cleaned(indicator_id = "hvYqrmR6MPq",
                       months = c(),
                       year = input$year,
                       organisation_uint = c("LEVEL-1", "LEVEL-2","LEVEL-3")
                       )

```


```{r}
measles_coverage_map <- get_coverage_map(annual_data = measles1_coverage_annually,
                 monthly_data = measles1_coverage_monthly)

dbAppendTable(connection, name = "measles_coverage_map", value = measles_coverage_map )

```


```{r}
measles_cases_map <- measles_sormas_cleaned %>%
  select("##Case ID","Disease", "Long", "Lat", "Months", "Year", "State", "LGA")


dbAppendTable(connection, name = "measles_cases_map", value = measles_cases_map )

```

