---
title: "Getting-all-dhis2-meningitis-data-2020-to-May-2022"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Getting-all-dhis2-meningitis-data-2020-to-May-2022}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(Dhis2WithSormas)
library(readr)
```



```{r}

# months_vector <- c("05")
# 
# meningitis_years <- c(2022)
# 

meningitis_first_year <- 2020

meningitis_years <-  c(2021, 2022)

months_vector <-  c("01","02","03","04","05","06","07","08", "09","10","11","12")

```


```{r}

dw <- config::get("development_stream2")

loginToDATIM(
  base_url = dw$Dhis2_base_url,
  username = dw$Dhis2_username,
  username = dw$Dhis2_username,
  password = dw$Dhis2_password
)
```


```{r}
meningitis_coverage_annualized <- getAnalytics_cleaned(indicator_id = "SruoPzzt3ES",
                       months = c(),
                       year = meningitis_first_year,
                       organisation_uint = c("LEVEL-1", "LEVEL-2","LEVEL-3")
                       )


for( year in meningitis_years) {
  
   print(year)
  
  data_for_that_year <- getAnalytics_cleaned(indicator_id =  "SruoPzzt3ES",
                       months =  c(),
                       year = year,
                       organisation_uint = c("LEVEL-1", "LEVEL-2","LEVEL-3")
                       )
  
  meningitis_coverage_annualized <-  bind_rows(meningitis_coverage_annualized,  data_for_that_year)
  
}

indicator_name <-  datimutils::getAnalytics(dx =  "SruoPzzt3ES",
                                         ou = "LEVEL-1",
                                         pe = "2020",
                                         return_names = T) %>% pull(Data) %>% unique()


meningitis_coverage_annualized <- meningitis_coverage_annualized %>% mutate(Indicator =indicator_name)

write_csv(x = meningitis_coverage_annualized,
          file = "/Volumes/Robinson/Afenet-projects/afenet-nigeria/Dhis2WithSormas/data-raw/meningitis_coverage_annualized.csv")

```


```{r}
meningitis_coverage_monthly <-  getAnalytics_cleaned(indicator_id = "SruoPzzt3ES",
                       months = months_vector,
                       year = meningitis_first_year,
                       organisation_uint = c("LEVEL-1", "LEVEL-2","LEVEL-3"))


for( year in meningitis_years) {
  
   print(year)
  
  data_for_that_year <-  getAnalytics_cleaned(indicator_id = "SruoPzzt3ES",
                       months = months_vector,
                       year = year,
                       organisation_uint = c("LEVEL-1", "LEVEL-2","LEVEL-3"))
  
  meningitis_coverage_monthly <-  bind_rows(meningitis_coverage_monthly,  data_for_that_year)}

indicator_name <-  datimutils::getAnalytics(dx =  "SruoPzzt3ES",
                                         ou = "LEVEL-1",
                                         pe = "2020",
                                         return_names = T) %>% pull(Data) %>% unique()


meningitis_coverage_monthly <- meningitis_coverage_monthly %>% mutate(Indicator =indicator_name)

write_csv(x = meningitis_coverage_monthly,
          file = "/Volumes/Robinson/Afenet-projects/afenet-nigeria/Dhis2WithSormas/data-raw/meningitis_coverage_monthly.csv")
```





```{r}
men_A_given <-  getAnalytics_cleaned(indicator_id = "iOUKrRANJwi",
                       months = months_vector,
                       year = meningitis_first_year,
                       organisation_uint = c("LEVEL-1", "LEVEL-2","LEVEL-3"))




for( year in meningitis_years) {
  
   print(year)
  
  data_for_that_year <-  getAnalytics_cleaned(indicator_id = "iOUKrRANJwi",
                       months = months_vector,
                       year = year,
                       organisation_uint = c("LEVEL-1", "LEVEL-2","LEVEL-3"))
  
  
  
  men_A_given <-  bind_rows(men_A_given,  data_for_that_year)}



indicator_name <-  datimutils::getAnalytics(dx =  "iOUKrRANJwi",
                                         ou = "LEVEL-1",
                                         pe = "2020",
                                         return_names = T) %>% pull(Data) %>% unique()




men_A_given <- men_A_given %>% mutate(Indicator =indicator_name)

write_csv(x = men_A_given,
          file = "/Volumes/Robinson/Afenet-projects/afenet-nigeria/Dhis2WithSormas/data-raw/men_A_given.csv")

```


```{r}
men_A_Received  <- getAnalytics_cleaned(indicator_id = "yH7RI3urgYi",
                       months = months_vector,
                       year = meningitis_first_year,
                       organisation_uint = c("LEVEL-1", "LEVEL-2","LEVEL-3")
                       )


for( year in meningitis_years) {
  
   print(year)
  
  data_for_that_year <- getAnalytics_cleaned(indicator_id = "yH7RI3urgYi",
                       months = months_vector,
                       year = year,
                       organisation_uint = c("LEVEL-1", "LEVEL-2","LEVEL-3")
                       )
  
  men_A_Received <-  bind_rows(men_A_Received,  data_for_that_year)
  
}

indicator_name <-  datimutils::getAnalytics(dx = "yH7RI3urgYi",
                                         ou = "LEVEL-1",
                                         pe = "2020",
                                         return_names = T) %>% pull(Data) %>% unique()


men_A_Received <- men_A_Received %>% mutate(Indicator =indicator_name)


write_csv(x = men_A_Received,
          file = "/Volumes/Robinson/Afenet-projects/afenet-nigeria/Dhis2WithSormas/data-raw/men_A_Received.csv")

```



```{r}
men_A_OB  <-  getAnalytics_cleaned(indicator_id = "BWBsbKHaCrz",
                       months = months_vector,
                       year = meningitis_first_year,
                       organisation_uint = c("LEVEL-1", "LEVEL-2","LEVEL-3")
                       )



for( year in meningitis_years) {
  
   print(year)
  
  data_for_that_year <- getAnalytics_cleaned(indicator_id = "BWBsbKHaCrz",
                       months = months_vector,
                       year = year,
                       organisation_uint = c("LEVEL-1", "LEVEL-2","LEVEL-3")
                       )
  
  men_A_OB <-  bind_rows(men_A_OB,  data_for_that_year)
  
}

indicator_name <-  datimutils::getAnalytics(dx = "BWBsbKHaCrz",
                                         ou = "LEVEL-1",
                                         pe = "2020",
                                         return_names = T) %>% pull(Data) %>% unique()


men_A_OB <- men_A_OB %>% mutate(Indicator =indicator_name)


write_csv(x = men_A_OB,
          file = "/Volumes/Robinson/Afenet-projects/afenet-nigeria/Dhis2WithSormas/data-raw/men_A_OB.csv")

```




```{r}
men_A_Doses_Opened  <- getAnalytics_cleaned(indicator_id = "snrl5tiWGLE",
                       months = months_vector,
                       year = meningitis_first_year,
                       organisation_uint = c("LEVEL-1", "LEVEL-2","LEVEL-3")
                       )




for( year in meningitis_years) {
  
   print(year)
  
  data_for_that_year <- getAnalytics_cleaned(indicator_id =  "snrl5tiWGLE",
                       months = months_vector,
                       year = year,
                       organisation_uint = c("LEVEL-1", "LEVEL-2","LEVEL-3")
                       )
  
  men_A_Doses_Opened <-  bind_rows(men_A_Doses_Opened,  data_for_that_year)
  
}

indicator_name <-  datimutils::getAnalytics(dx =  "snrl5tiWGLE",
                                         ou = "LEVEL-1",
                                         pe = "2020",
                                         return_names = T) %>% pull(Data) %>% unique()


men_A_Doses_Opened <- men_A_Doses_Opened %>% mutate(Indicator =indicator_name)

write_csv(x = men_A_Doses_Opened,
          file = "/Volumes/Robinson/Afenet-projects/afenet-nigeria/Dhis2WithSormas/data-raw/men_A_Doses_Opened.csv")
```


