---
title: "sormasr"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{sormasr}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


```{r setup}
library(Dhis2WithSormas)
library(dhis2r)
library(sormasr)
library(lubridate)
```


```{r}
# Create a new object of the Sormasr class and assign it to the sormas_connection variable.
sormas_connection <- Sormasr$new()


sormas_states <- sormas_connection$get_states(page = 0, size = 37)

state_ids <- sormas_states |>
  select(state_name, state_id) |>
  distinct() |>
  pull(state_id)


diseases = c("Measles", "CSM", "YellowFever")

#months = c("JANUARY", "FEBRUARY", "MARCH", "APRIL", "MAY", "JUNE", "JULY", "AUGUST", "SEPTEMBER", "OCTOBER", "NOVEMBER", "DECEMBER")

#months = c("JANUARY", "FEBRUARY", "MARCH", "APRIL", "MAY")

sormas_input <- list(year = "2023", month = "MAY", disease = "Measles")

#

disease_data <- sormas_connection$get_disease_data(disease = sormas_input$disease,
                                                   stateId =  "100323",
                                                   month = sormas_input$month,
                                                   year = sormas_input$year ,
                                                   page = "0",
                                                   size = "44") |> 
                                                    mutate( months = sormas_input$month,
                                                            year = sormas_input$year)



sormas_states_ids <- sort(unique(sormas_states$state_id))


for( sormas_states_id in  sormas_states_ids[-1]) {
      
          data_for_that_month <- sormas_connection$get_disease_data(disease =  sormas_input$disease,
                                                           stateId =  sormas_states_id,
                                                           month = sormas_input$month,
                                                           year =  sormas_input$year,
                                                           page = "0",
                                                           size = "44") |> 
                                                            mutate( months = sormas_input$month,
                                                                    year = sormas_input$year)
          
          disease_data <-  bind_rows(disease_data,    data_for_that_month)
          
}
  
 


 disease_data_cleaned <-  disease_data |> 
   mutate(state = case_when(state == "Fct" ~ "Federal Capital Territory", TRUE ~as.character(state)),
         months = stringr::str_to_sentence(stringr::str_trunc(months,3, ellipsis = "")),
         year = as.numeric(year)) |> 
   select(-c(state_id, lga_id )) |> 
  setNames(c("State", "LGA", "Confirmed_cases","Months", "Year"))


 disease_data_cleaned
```


```{r}
age_sex_data <- sormas_connection$get_age_sex(disease = sormas_input$disease, 
                                    stateId = "100323",
                                    month = sormas_input$month,
                                    vaccinationStatus = "true",
                                    year = sormas_input$year,
                                    page = "0", 
                                    size = "44")|> 
                                    mutate( months = sormas_input$month,
                                            year = sormas_input$year)


for( sormas_states_id in  sormas_states_ids[-1]) {
  
  
  age_sex_month_data <- age_sex_data <- sormas_connection$get_age_sex(disease = sormas_input$disease, 
                                    stateId = sormas_states_id,
                                    month = sormas_input$month,
                                    vaccinationStatus = "true",
                                    year = sormas_input$year,
                                    page = "0", 
                                    size = "44")|> 
                                    mutate( months = sormas_input$month,
                                            year = sormas_input$year,)

  
  age_sex_data  <-  bind_rows(age_sex_data  ,  age_sex_month_data)
  
}

   
```

## Maps

```{r}
disease_data_map <-disease_data %>%
  setNames(c("state","lga", "year", "months",  ))
  select("Months", "Year", "State", "LGA", "Confirmed_cases")


```

