---
title: "updating_remote_database_diphtheria"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{updating_remote_database_diphtheria}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(Dhis2WithSormas)

dw <- config::get("development_stream2")

connection <- DBI::dbConnect(RMariaDB::MariaDB(),
               username = dw$DB_user,
               password = dw$DB_password,
               host     = dw$DB_host,
               port     = dw$DB_port,
               dbname   = dw$DB_name)
```

## Confirmed diphtheria cases, penta1, penta3 doses
```{r}
diphtheria_sormas_cleaned <- sormas_cleaner("/Volumes/Robinson/Afenet-projects/afenet-nigeria/Dhis2WithSormas/data-raw/sormas_diphtheria_cases_2017_2023.csv", disease = "diphtheria")

penta1_coverage_monthly <- read_csv("/Volumes/Robinson/Afenet-projects/afenet-nigeria/Dhis2WithSormas/data-raw/penta1_coverage_monthly.csv")

penta3_coverage_monthly <- read_csv("/Volumes/Robinson/Afenet-projects/afenet-nigeria/Dhis2WithSormas/data-raw/penta3_coverage_monthly.csv")

penta1_given <- read_csv("/Volumes/Robinson/Afenet-projects/afenet-nigeria/Dhis2WithSormas/data-raw/penta1_given.csv")

penta3_given <-read_csv("/Volumes/Robinson/Afenet-projects/afenet-nigeria/Dhis2WithSormas/data-raw/penta3_given.csv")
```



```{r}
diphtheria_alt_denominator <- get_2_dose_alt_denominator(sormas_cleaned = diphtheria_sormas_cleaned,
                            first_dose = penta1_coverage_monthly,
                            later_dose = penta3_coverage_monthly,
                            first_dose_given = penta1_given,
                            later_dose_given = penta3_given,
                            denominator_data = denominator_data)

#dbWriteTable(connection , name = "diphtheria_alt_denominator", value = diphtheria_alt_denominator %>% slice(1:2), overwrite = TRUE)

updated_remote_database(connection = connection,
                        dataset = bind_rows( filter(diphtheria_alt_denominator, State == "Federal Capital Territory"),
                                             filter(diphtheria_alt_denominator, State != "Federal Capital Territory") ),
                        aws_datatable = "diphtheria_alt_denominator", 
                       starting_index = 1)
#finished
```

# Age group 

```{r}

diphtheria_age_group <- get_age_group(sormas_cleaned = diphtheria_sormas_cleaned)

dbWriteTable(connection, name = "diphtheria_age_group", value = diphtheria_age_group %>% slice(1:2), overwrite = TRUE)

updated_remote_database(connection = connection,
                        dataset = bind_rows( filter(diphtheria_age_group, State == "Federal Capital Territory"),
                                                 filter(diphtheria_age_group, State != "Federal Capital Territory") ), 
                            aws_datatable = "diphtheria_age_group",
                            starting_index = 1)



```
# Chart 3: Penta Stock Analysis & Penta (1 & 3) given


```{r}
penta2_given <- read_csv("/Volumes/Robinson/Afenet-projects/afenet-nigeria/Dhis2WithSormas/data-raw/penta2_given.csv")

penta_1_3_given <- add_three_dose_antigen_given(first_dose_given = penta1_given,
                                                second_dose_given = penta2_given,
                                                third_dose_given = penta3_given,
                                                      antigen = "Penta")

penta_received <- read_csv("/Volumes/Robinson/Afenet-projects/afenet-nigeria/Dhis2WithSormas/data-raw/penta_Received.csv")

penta_opening_balance <- read_csv("/Volumes/Robinson/Afenet-projects/afenet-nigeria/Dhis2WithSormas/data-raw/penta_OB.csv")

penta_opened_used <- read_csv("/Volumes/Robinson/Afenet-projects/afenet-nigeria/Dhis2WithSormas/data-raw/penta_opened_used.csv")

```


```{r}

penta_stock_analysis <- get_stock_analysis(doses_given = penta_1_3_given,
                                        received = penta_received,
                                        opening_balance = penta_opening_balance,
                                        opened_used = penta_opened_used)

#dbWriteTable(connection, name = "penta_stock_analysis", value = penta_stock_analysis %>% slice(1:2), overwrite = TRUE)

updated_remote_database(connection, 
                        dataset = bind_rows( filter(penta_stock_analysis, State == "Federal Capital Territory"), filter(penta_stock_analysis, State != "Federal Capital Territory") ), 
                     
                     aws_datatable = "penta_stock_analysis",starting_index = 27001)

```

## Penta 1, Penta 3 Coverage & Drop Out Rate


```{r}
penta1_penta3_dropout_rate <- get_drop_out_rate(first_dose  = penta1_coverage_monthly,
                                                later_dose =  penta3_coverage_monthly)

#dbWriteTable(connection, name = "penta1_penta3_dropout_rate", value = penta1_penta3_dropout_rate %>% slice(1:2), overwrite = TRUE)

updated_remote_database(connection,
  dataset = bind_rows( filter(penta1_penta3_dropout_rate, State == "Federal Capital Territory"),
                       filter(penta1_penta3_dropout_rate, State != "Federal Capital Territory") ), 
  aws_datatable = "penta1_penta3_dropout_rate",
  starting_index = 65001)

## skipped 62000
## Penta you start with 60001, I have put it there

```

## Co-administered Antigen Discrepancy: Penta 1 & OPV1 given by State

```{r}
opv1_given <- read_csv("/Volumes/Robinson/Afenet-projects/afenet-nigeria/Dhis2WithSormas/data-raw/opv1_given.csv")
```


```{r}

penta1_opv1_discrepancy <- get_discrepancy(main_vaccine_given = penta1_given, 
                                                        other_vaccine_given = opv1_given)


dbWriteTable(connection, name = "penta1_opv1_discrepancy", 
             value = penta1_opv1_discrepancy %>% slice(1:2), overwrite = TRUE)

updated_remote_database(connection,
  dataset = bind_rows( filter(penta1_opv1_discrepancy, State == "Federal Capital Territory"),
                       filter(penta1_opv1_discrepancy, State != "Federal Capital Territory") ), 
                     
                     aws_datatable = "penta1_opv1_discrepancy",starting_index = 64001)
```

## National Penta Coverage (%) by different sources, Nigeria (National)

```{r}
penta1_coverage_annualized_all_time <- read_csv("/Volumes/Robinson/Afenet-projects/afenet-nigeria/Dhis2WithSormas/data-raw/penta1_coverage_annualized_all_time.csv")

penta3_coverage_annualized_all_time <- read_csv("/Volumes/Robinson/Afenet-projects/afenet-nigeria/Dhis2WithSormas/data-raw/penta3_coverage_annualized_all_time.csv")|> mutate(Values = round(Values/12, 1))
```


```{r}
# Data aggregated by Year, State


penta_different_sources <- get_penta_different_sources(
  penta1_coverage_annualized_all_time =penta1_coverage_annualized_all_time,
  penta3_coverage_annualized_all_time = penta3_coverage_annualized_all_time)

dbWriteTable(connection, name = "penta_different_sources", value = penta_different_sources, overwrite = TRUE)

```

## Map Confirmed penta cases, Penta 1 coverage


```{r}
penta1_coverage_annually <- read_csv("/Volumes/Robinson/Afenet-projects/afenet-nigeria/Dhis2WithSormas/data-raw/penta1_coverage_annualized.csv")

```


```{r}
penta_coverage_map <- get_coverage_map(annual_data = penta1_coverage_annually,
                 monthly_data = penta1_coverage_monthly)


dbWriteTable(connection, name = "penta_coverage_map", 
             value = penta_coverage_map %>% slice(1:2), overwrite = TRUE)

updated_remote_database(connection,
  dataset = bind_rows( filter(penta_coverage_map, State == "Federal Capital Territory"),
                       filter(penta_coverage_map, State != "Federal Capital Territory") ),
  aws_datatable = "penta_coverage_map",starting_index = 4001)


```


```{r}
#diphtheria_cases_map <- diphtheria_sormas_cleaned%>%
#  select("##Case ID","Disease", "Long", "Lat", "Months", "Year", "State", "LGA")


dbWriteTable(connection, name = "diphtheria_cases_map", 
             value = diphtheria_cases_map %>% slice(1:2), overwrite = TRUE)

updated_remote_database(connection = connection,
  dataset = bind_rows( filter(diphtheria_cases_map, State == "Federal Capital Territory"),
                       filter(diphtheria_cases_map, State != "Federal Capital Territory") ), 
                     
                     aws_datatable = "diphtheria_cases_map",starting_index = 1)


```

