---
title: "updating_remote_database_meningitis"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{updating_remote_database_meningitis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(Dhis2WithSormas)
library(readr)
```

```{r}
dw <- config::get("development_stream2")

connection <- DBI::dbConnect(RMariaDB::MariaDB(),
               username = dw$DB_user,
               password = dw$DB_password,
               host     = dw$DB_host,
               port     = dw$DB_port,
               dbname   = dw$DB_name)
```




##   Confirmed Meningitis cases, Meningitis coverage, ALt D

```{r}
sormas_meningitis_cleaned <- sormas_cleaner("/Volumes/Robinson/Afenet-projects/Dhis2WithSormas/data-raw/sormas_meningitis.csv")

men_A_coverage_monthly <- read_csv("/Volumes/Robinson/Afenet-projects/Dhis2WithSormas/data-raw/meningitis_coverage_monthly.csv")

men_A_given <- read_csv("/Volumes/Robinson/Afenet-projects/Dhis2WithSormas/data-raw/men_A_given.csv")

```

```{r}

men_A_alt_denominator <- get_alt_denominator(coverage = men_A_coverage_monthly,
                    sormas_cleaned = sormas_meningitis_cleaned ,
                    doses_given = men_A_given, 
                    denominator_data = denominator_data)

#dbWriteTable(connection , name = "men_A_alt_denominator", value = men_A_alt_denominator %>% slice(1:2), overwrite = TRUE)

updated_remote_database(connection = connection,
                        dataset = bind_rows( filter(men_A_alt_denominator, State == "Federal Capital Territory"),
                                             filter(men_A_alt_denominator, State != "Federal Capital Territory") ),
                        aws_datatable = "men_A_alt_denominator", 
                       starting_index = 1)
```

## Age Group of Confirmed Meningitis Cases by Vaccination Status

```{r}

meningitis_age_group <- get_age_group(sormas_cleaned = sormas_meningitis_cleaned)

#dbWriteTable(connection, name = "meningitis_age_group", value = meningitis_age_group %>% slice(1:2), overwrite = TRUE)

updated_remote_database(connection = connection,
                        dataset = bind_rows( filter(meningitis_age_group, State == "Federal Capital Territory"),
                                                 filter(meningitis_age_group, State != "Federal Capital Territory") ), 
                            aws_datatable = "meningitis_age_group",
                            starting_index = 1)

```

## Men A Stock Analysis & Men A given


```{r}

men_A_received <- read_csv("/Volumes/Robinson/Afenet-projects/Dhis2WithSormas/data-raw/men_A_Received.csv")

men_A_opening_balance <- read_csv("/Volumes/Robinson/Afenet-projects/Dhis2WithSormas/data-raw/men_A_OB.csv")

men_A_opened_used <- read_csv("/Volumes/Robinson/Afenet-projects/Dhis2WithSormas/data-raw/men_A_Doses_Opened.csv")

```

```{r}
men_A_stock_analysis <- get_stock_analysis(doses_given = men_A_given,
                                        received = men_A_received,
                                        opening_balance = men_A_opening_balance,
                                        opened_used = men_A_opened_used)

#dbWriteTable(connection, name = "men_A_stock_analysis", value = men_A_stock_analysis %>% slice(1:2), overwrite = TRUE)

updated_remote_database(connection = connection,
                        dataset = bind_rows( filter(men_A_stock_analysis, State == "Federal Capital Territory"),
                                             filter(men_A_stock_analysis, State != "Federal Capital Territory") ), 
                     
                     aws_datatable = "men_A_stock_analysis",starting_index = 1)
```

## Co-administered Antigen Discrepancy: MCV 1 & Men A given by State
```{r}

measles1_given <- read_csv("/Volumes/Robinson/Afenet-projects/Dhis2WithSormas/data-raw/measles1_given.csv")

```



```{r}
measles_men_A_discrepancy <- get_discrepancy(main_vaccine_given = measles1_given, 
                                                        other_vaccine_given = men_A_given)


#dbWriteTable(connection, name = "measles_men_A_discrepancy", value = measles_men_A_discrepancy %>% slice(1:2), overwrite = TRUE)

updated_remote_database(
  dataset = bind_rows( filter(measles_men_A_discrepancy, State == "Federal Capital Territory"),
                       filter(measles_men_A_discrepancy, State != "Federal Capital Territory") ), 
                     
                     aws_datatable = "measles_men_A_discrepancy",starting_index = 1)
```

## Map Confirmed Meningitis cases, Meningitis coverage


## Map Confirmed men_A cases, MCV 1 coverage


```{r}
men_A_coverage_annually <- read_csv("/Volumes/Robinson/Afenet-projects/Dhis2WithSormas/data-raw/meningitis_coverage_annualized.csv")

```


```{r}
men_A_coverage_map <- get_coverage_map(annual_data = men_A_coverage_annually,
                 monthly_data = men_A_coverage_monthly)


dbWriteTable(connection, name = "men_A_coverage_map", 
             value = men_A_coverage_map %>% slice(1:2), overwrite = TRUE)

updated_remote_database(
  dataset = bind_rows( filter(men_A_coverage_map, State == "Federal Capital Territory"),
                       filter(men_A_coverage_map, State != "Federal Capital Territory") ), 
                     
                     aws_datatable = "men_A_coverage_map",starting_index = 1)


```


```{r}
meningitis_cases_map <- sormas_meningitis_cleaned%>%
  select("##Case ID","Disease", "Long", "Lat", "Months", "Year", "State", "LGA")


#dbWriteTable(connection, name = "meningitis_cases_map", 
 #            value = meningitis_cases_map %>% slice(1:2), overwrite = TRUE)

updated_remote_database(
  dataset = bind_rows( filter(meningitis_cases_map, State == "Federal Capital Territory"),
                       filter(meningitis_cases_map, State != "Federal Capital Territory") ), 
                     
                     aws_datatable = "meningitis_cases_map",starting_index = 1)


```

